services:
  db:
    image: postgres:latest
    container_name: line-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: line_bot_db
      POSTGRES_USER: lineBotUser
      POSTGRES_PASSWORD: lineBotPassword
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
